name: Deploy Apache EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      # 🔍 Debug para verificar que el host sí se está leyendo
      - name: Debug EC2_HOST
        run: |
          if [ -z "${{ secrets.EC2_HOST }}" ]; then
            echo "❌ EC2_HOST está vacío"
            exit 1
          else
            echo "✅ EC2_HOST detectado"
          fi

      - name: Deploy a EC2 vía SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 98.82.181.101   # 👈 TEMPORAL (para asegurar que funcione)
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            echo "🚀 Deploy iniciado"

            if [ ! -d "deploy-ec2" ]; then
              git clone https://github.com/yaquelin2305/deploy-ec2.git
            fi

            cd deploy-ec2

            git fetch origin
            git reset --hard origin/main

            sudo cp index.html /var/www/html/index.html
            sudo systemctl restart apache2

            echo "✅ Deploy terminado"